name: "Infra Pipeline"
on: workflow_dispatch
permissions:
  contents: read
  issues: write
jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install Terraform
 
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.13.0
      - name: Azure Login
        uses: Azure/login@v2.3.0 
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          
          # ClientId of the Azure Service principal created.
          client-id: 268c860a-2986-439e-85f4-691239f7be9f
          # TenantId of the Azure Service principal created.
          tenant-id: c1458e86-22a3-4b4c-b4af-89ecd5384a8f
          # Azure subscriptionId
          subscription-id: 5e4fafbb-ef69-4e17-8835-68030d81f758
          # Set this value to true to enable Azure PowerShell Login in addition to Azure CLI login
         
                
      
          
          
    
